### ISSUE TITLE
Table name question

### ISSUE THREAD

**Issue by rettal** [utopia-php/audit#1]
Hi,

Cool, simple little lib, and easy to use and extend 👍 Just wondering why the table name is "namespace.audit.audit", I get the namespace part but why is "audit" repeated? I know it's a pretty inane question but just wondering in case I am missing something?

Thanks for sharing 😊

**Comment by eldadfux** [comment]
Probably just because we use this convention a lot on Appwrite (https://github.com/appwrite).

`namespace.[service].[table]`

When we have just one table we just repeat the service name for it, similar to the how namespaces conventions work in PHP.
